# Based on https://github.com/Bioconductor/BiocManager/blob/master/.travis.yml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - bioc-devel
  - bioc-release

os:
  - linux
  - osx

# Strict checks in place
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
